volumes:
    postgress-data:
    images:
services:
  php:
    build:
      context: ./docker/php/
      dockerfile: dev.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/app/
      - images:/images/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - pgsql
    user: 1000:1001
  node:
    image: node:20
    ports:
      - 5173:5173
    volumes:
      - ./:/app/
    working_dir: /app/
    command: "npm run dev"
    user: 1000:1001
  pgsql:
    image: postgres:16
    shm_size: '1gb'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: laravel
    volumes:
            - 'postgress-data:/var/lib/postgresql/data'
    ports:
            - '127.0.0.1:5432:5432'
    command: postgres -c max_locks_per_transaction=1024 -c logging_collector=on -c log_statement=all -c log_directory=logs
